/**
 * Pages & Items API
 * An API to manage pages & items
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { PageAttributesValue } from '../models/PageAttributesValue';
import { HttpFile } from '../http/http';

export class Item {
    /**
    * The item's ID.
    */
    'id': string;
    /**
    * The item's name.
    */
    'name'?: string;
    /**
    * Item attributes, key-value pairs.
    */
    'attributes'?: { [key: string]: PageAttributesValue; };
    /**
    * The content of the item.
    */
    'content'?: string;
    /**
    * The ID of the parent page or item.
    */
    'parent': string;
    /**
    * The type of the item.
    */
    'type': ItemTypeEnum;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "attributes",
            "baseName": "attributes",
            "type": "{ [key: string]: PageAttributesValue; }",
            "format": ""
        },
        {
            "name": "content",
            "baseName": "content",
            "type": "string",
            "format": ""
        },
        {
            "name": "parent",
            "baseName": "parent",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "ItemTypeEnum",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return Item.attributeTypeMap;
    }

    public constructor() {
    }
}


export type ItemTypeEnum = "dynamic" | "list" | "news" | "project" | "event" ;

