/**
 * Pages & Items API
 * An API to manage pages & items
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Item } from '../models/Item';
import { Metadata } from '../models/Metadata';
import { PageAttributesValue } from '../models/PageAttributesValue';
import { HttpFile } from '../http/http';

export class Page {
    /**
    * The page's ID.
    */
    'id': string;
    /**
    * The page's name.
    */
    'name'?: string;
    /**
    * Page attributes, key-value pairs.
    */
    'attributes'?: { [key: string]: PageAttributesValue; };
    /**
    * The ID of the parent page, if any.
    */
    'parent'?: string;
    'metadata'?: Metadata;
    /**
    * The items associated with the page.
    */
    'items'?: Array<Item>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "attributes",
            "baseName": "attributes",
            "type": "{ [key: string]: PageAttributesValue; }",
            "format": ""
        },
        {
            "name": "parent",
            "baseName": "parent",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "metadata",
            "baseName": "metadata",
            "type": "Metadata",
            "format": ""
        },
        {
            "name": "items",
            "baseName": "items",
            "type": "Array<Item>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return Page.attributeTypeMap;
    }

    public constructor() {
    }
}

