openapi: 3.0.2
info:
  description: An API to manage pages & items
  title: Pages & Items API
  version: 1.0.0
servers:
- url: /
paths:
  /pages:
    post:
      operationId: pagesPOST
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Page'
        required: true
      responses:
        "201":
          description: Page created
        "400":
          description: Invalid input
        "401":
          description: Unauthorized
      security:
      - ApiKeyAuth: []
      summary: Create a new page
      x-eov-operation-handler: controllers/DefaultController
  /pages/{id}:
    delete:
      operationId: pagesIdDELETE
      parameters:
      - explode: false
        in: path
        name: id
        required: true
        schema:
          format: uuid
          type: string
        style: simple
      responses:
        "204":
          description: Page deleted
        "401":
          description: Unauthorized
        "404":
          description: Page not found
      security:
      - ApiKeyAuth: []
      summary: Delete a page
      x-eov-operation-handler: controllers/DefaultController
    put:
      operationId: pagesIdPUT
      parameters:
      - explode: false
        in: path
        name: id
        required: true
        schema:
          format: uuid
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Page'
        required: true
      responses:
        "200":
          description: Page updated
        "400":
          description: Invalid input
        "401":
          description: Unauthorized
        "404":
          description: Page not found
      security:
      - ApiKeyAuth: []
      summary: Update a page
      x-eov-operation-handler: controllers/DefaultController
  /items:
    post:
      operationId: itemsPOST
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Item'
        required: true
      responses:
        "201":
          description: Item created
        "400":
          description: Invalid input
        "401":
          description: Unauthorized
      security:
      - ApiKeyAuth: []
      summary: Create a new item
      x-eov-operation-handler: controllers/DefaultController
  /items/{id}:
    delete:
      operationId: itemsIdDELETE
      parameters:
      - explode: false
        in: path
        name: id
        required: true
        schema:
          format: uuid
          type: string
        style: simple
      responses:
        "204":
          description: Item deleted
        "401":
          description: Unauthorized
        "404":
          description: Item not found
      security:
      - ApiKeyAuth: []
      summary: Delete an item
      x-eov-operation-handler: controllers/DefaultController
    put:
      operationId: itemsIdPUT
      parameters:
      - explode: false
        in: path
        name: id
        required: true
        schema:
          format: uuid
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Item'
        required: true
      responses:
        "200":
          description: Item updated
        "400":
          description: Invalid input
        "401":
          description: Unauthorized
        "404":
          description: Item not found
      security:
      - ApiKeyAuth: []
      summary: Update an item
      x-eov-operation-handler: controllers/DefaultController
components:
  schemas:
    Page:
      example:
        parent: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        metadata:
          keywords:
          - keywords
          - keywords
          description: description
          robots: robots
          title: title
        name: name
        attributes:
          key: Page_attributes_value
        id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        items:
        - parent: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
          name: name
          attributes:
            key: null
          id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
          type: dynamic
          content: content
        - parent: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
          name: name
          attributes:
            key: null
          id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
          type: dynamic
          content: content
      properties:
        id:
          description: The page's ID.
          format: uuid
          type: string
        name:
          description: The page's name.
          type: string
        attributes:
          additionalProperties:
            $ref: '#/components/schemas/Page_attributes_value'
          description: "Page attributes, key-value pairs."
          type: object
        parent:
          description: "The ID of the parent page, if any."
          format: uuid
          type: string
        metadata:
          $ref: '#/components/schemas/Metadata'
        items:
          description: The items associated with the page.
          items:
            $ref: '#/components/schemas/Item'
          type: array
      required:
      - id
      type: object
    Metadata:
      description: The metadata of the page.
      example:
        keywords:
        - keywords
        - keywords
        description: description
        robots: robots
        title: title
      properties:
        title:
          type: string
        description:
          type: string
        robots:
          type: string
        keywords:
          items:
            type: string
          type: array
      type: object
    Item:
      example:
        parent: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        name: name
        attributes:
          key: null
        id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        type: dynamic
        content: content
      properties:
        id:
          description: The item's ID.
          format: uuid
          type: string
        name:
          description: The item's name.
          type: string
        attributes:
          additionalProperties:
            $ref: '#/components/schemas/Page_attributes_value'
          description: "Item attributes, key-value pairs."
          type: object
        content:
          description: The content of the item.
          type: string
        parent:
          description: The ID of the parent page or item.
          format: uuid
          type: string
        type:
          description: The type of the item.
          enum:
          - dynamic
          - list
          - news
          - project
          - event
          type: string
      required:
      - id
      - parent
      - type
      type: object
    Page_attributes_value:
      oneOf:
      - type: string
      - type: integer
      - enum:
        - Option1
        - Option2
        type: string
  securitySchemes:
    ApiKeyAuth:
      in: header
      name: X-Api-Key
      type: apiKey
