name: Workflow Settings

on:
  workflow_dispatch:  # Manual trigger

permissions:
  actions: read
  contents: read
  pull-requests: write
  checks: write
  deployments: read
  
jobs:
  default-settings:
    runs-on: ubuntu-latest
    steps:
      - name: Set Default Workflow Permissions
        run: echo "Setting default workflow permissions"